jobs:
  gotest:
    name: GoTest
    runs-on: [self-hosted, linux]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Checkout
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.*'
      - name: Go Env
        run: |
          go env
